[versions]
kotlin = "2.2.20"
fritz2 = "1.0-RC21"

[libraries]
fritz2-core = { module = "dev.fritz2:core", version.ref = "fritz2" }
fritz2-headless = { module = "dev.fritz2:headless", version.ref = "fritz2" }
fritz2-lenses = { group = "dev.fritz2", name = "lenses-annotation-processor", version.ref = "fritz2" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version = "2.2.20-2.0.4" }